newproj/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path, include
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls1', namespace="myapp")),

]

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=300, default='windsor')

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100)
    available = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    interested = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def refill(self, name1):
        product = Product.objects.get(name=name1)
        product.stock = product.stock + 100
        product.save()
        return self.stock

class Client(User):
    PROVINCE_CHOICES = [
        ('AB', 'Alberta'),
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    ]
    company = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=30, default='windsor')

    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20)
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)
    picture = models.ImageField(upload_to='myapp/images', null=True, blank=True)

    def __str__(self):
        return self.username

class Order(models.Model):
    STATUS_CHOICES = [
                    (0, 'Order Cancelled'),
                    (1, 'Order Placed'),
                    (2, 'Order Shipped'),
                    (3, 'Order Delivered'),
    ]
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    num_unit = models.PositiveIntegerField(default=100)
    order_status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    status_date = models.DateField(default=timezone.now)

    def __str__(self):
        return str(self.product)


    def total_cost(self, product):
        od = Order.objects.filter(product__name=product)
        pr = Product.objects.filter(name=product)
        x = pr.values()[0].get('price')
        y = od.values()[0].get('num_unit')
        return x*y

class ImagesTable(models.Model):
    title = models.CharField(max_length=100)
    picture = models.ImageField(upload_to='myapp/images')
    client = models.OneToOneField(Client, on_delete=models.CASCADE)

myapp/forms.py
from django import forms
from myapp.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('product', 'client', 'num_unit')
        widgets = {
            'client': forms.RadioSelect(attrs={'class': 'radio'}),
        }
        labels = {
            'client': "Client Name",
            'num_unit': "Quantity",
        }


class InterestForm(forms.Form):

    CHOICES = (('1', 'Yes',), ('0', 'No',))
    interested = forms.CharField(widget=forms.RadioSelect(choices=CHOICES))
    quantity = forms.IntegerField(initial=1)
    comments = forms.CharField(widget=forms.Textarea(), required=False, label="Additional Comments")

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'required': True, 'class': 'validate', 'placeholder': 'Username'}), label="")
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'required': True, 'class': 'validate input-field', 'placeholder': 'Password'}),
        label="")

class UploadImageForm(forms.Form):
    title = forms.CharField( max_length=100)
    imgfile = forms.ImageField()

myapp/views.py
import datetime
import os
import random

from django.contrib.sessions import serializers
from  django.core.mail import send_mail

from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, SESSION_KEY, BACKEND_SESSION_KEY
from django.contrib.auth.decorators import login_required, user_passes_test

from myapp import forms
from myapp.forms import OrderForm, InterestForm, LoginForm, UploadImageForm
from myapp.models import Category, Product, Client, Order, ImagesTable
from django.shortcuts import get_object_or_404
from django.shortcuts import render


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        testuser = request.user

    else:
        testuser = ""



    cat_list = Category.objects.all().order_by('id')[:10]  #query to print list of categories
    prod_list = Product.objects.all().order_by('-price')[:5]  #query to print list of product in descending order of price
    response = HttpResponse()
    heading1 = '<p>' + 'List of Categories: ' + '</p>'
    response.write(heading1)
    for category in cat_list:
        para = '<p>' + str(category.id) + ': ' + str(category.name) + '</p>'
        response.write(para)
    heading1 = '<p>' + 'List of Product: ' + '</p>'
    response.write(heading1)
    for product in prod_list:
        para1 = '<p>' + str(product.id) + ': ' + str(product.name) + '</p>'
        response.write(para1)
    return render(request, 'myapp/index.html', {'cat_list': cat_list, 'prod_list': prod_list, 'testuser': testuser})


def about(request):
    if request.user.is_authenticated:
        testuser = request.user

    else:
        testuser = ""

    if 'about_visits' in request.COOKIES:
        about_visits = int(request.COOKIES['about_visits'])
        about_visits += 1
        response = render(request, 'myapp/about.html', {'about_visits': about_visits, 'testuser': testuser })
        response.set_cookie('about_visits', about_visits, max_age=300)
        return response
    else:
        about_visits = 1
        response = render(request, 'myapp/about.html', {'about_visits': about_visits, 'testuser': testuser})
        response.set_cookie('about_visits', about_visits)
        return response

def detail(request, cat_no):
    if request.user.is_authenticated:
        testuser = request.user

    else:
        testuser = ""



    get_object_or_404(Category, id=cat_no)  # page not found error if cat_no is not found
    try:
        category = Category.objects.get(id=cat_no)  #query to get category name with the id passed in cat_no
        product = Product.objects.filter(category=cat_no) #query to get list of product name with the id passed in cat_no

        response = HttpResponse()  #HTTPResponse
        cat_name = '<p>' + 'Category Name: ' + str(category.name) +'</p>'
        warehouse_name = '<p>' + 'Warehouse Name: ' + str(category.warehouse) + '</p>'

        response.write(cat_name)
        response.write(warehouse_name)

    # loop to print multiple objects of product for every category
        for prod in product:
            product_name = '<p>' + 'Product Name: ' + str(prod.name) + '</p>'
            response.write(product_name)
        #return response
        return render(request, 'myapp/detail.html', {'cat_name': category, 'product': product, 'testuser': testuser})
    except (KeyError, Category.DoesNotExist):
        print("Page not found (404)")


def products(request):
    if request.user.is_authenticated:
        testuser = request.user

    else:
        testuser = ""

    prodlist = Product.objects.all().order_by('id')
    return render(request, 'myapp/products.html', {'prodlist': prodlist, 'testuser': testuser})


def place_order(request):
    if request.user.is_authenticated:
        testuser = request.user

    else:
        testuser = ""

    msg = ''
    prodlist = Product.objects.all()
    if request.method == 'POST':
        form = forms.OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_unit <= order.product.stock:
                product = Product.objects.get(name = order.product.name)
                product.stock = product.stock - order.num_unit
                product.save()
                msg = 'Your order has been placed successfully.'
                p = Product()
                p.refill(order.product.name)
                order.save()
            else:
                msg = 'We do not have sufficient stock to fill your order.'
                p = Product()
                p.refill(order.product.name)
                order.save()
            return render(request, 'myapp/order_response.html', {'msg': msg, 'testuser': testuser})
            # else:
            #     msg = "Invalid user, select logged in user to place order"
            #     return render(request, 'myapp/order_response.html', {'msg': msg, 'testuser': testuser})
    else:
        form = OrderForm()
        return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prodlist': prodlist, 'testuser': testuser})


def productdetail(request, prod_id):
    if request.user.is_authenticated:
        testuser = request.user

    else:
        testuser = ""

    msg = ''
    prod_list = Product.objects.filter(id=prod_id)
    if request.method == 'POST':
        form = forms.InterestForm(request.POST)
        if form.is_valid():
            if request.POST['interested'] == '1':
                prod = Product.objects.get(id=prod_id)
                prod.interested += 1
                prod.save()
                msg = 'Your interest is updated successfully.'
            else:
                msg = 'Your interest is not updated successfully.'
        return render(request, 'myapp/index.html', {'form': form, 'prod_list': prod_list, 'msg': msg, 'testuser': testuser})
    else:
        form = InterestForm()
        return render(request, 'myapp/productdetail.html', {'form': form, 'prod_list': prod_list, 'msg': msg, 'testuser': testuser})


def user_login(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cli = Client.objects.get(username=username)
        user = authenticate(request, username=username, password=password)
        request.session.set_expiry(3600)
        if user:
            if user.is_active:
                if 'last_login' in request.session:
                    last_login = request.session.get('last_login')
                else:
                    currentDT = datetime.datetime.now()
                    request.session['last_login'] = str(currentDT.strftime("%d-%m-%Y %H:%M"))
                login(request, user)

                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled')

        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html', {'form': form})

@login_required
def user_logout(request):
    # del request.session['cli']

    # response.delete_cookie('about_visits')
    logout(request)
    response = HttpResponseRedirect(reverse('myapp:index'))
    return response

def myorders(request):
    if request.user.is_authenticated:
        testuser = request.user

        myorder = Order.objects.filter(client__username=request.user)
        return render(request, 'myapp/myorders.html', {'myorder': myorder, 'testuser': testuser})

    else:
        testuser = ""
        message = 'login please'
        return render(request, 'myapp/myorders.html', {'message': message, 'testuser': testuser})



# def forgotpass(request):
#     if request.method == 'POST':
#         username = request.POST['username']
#         t_user = Client.objects.get(username=username)
#         password = str(os.urandom(8))
#         t_user.set_password(password)
#         t_user.save()
#         send_mail(
#              'MyApp Password',
#              'Your new Password is:' + password,
#              'Email',
#              [t_user.email],
#          )
#         return render(request, 'myapp/forgotpass.html', {'emailSent': True})
#     else:
#         return render(request, 'myapp/forgotpass.html')

def upload_form(request):
    saved  = False
    if request.user.is_authenticated:
        testuser = request.user
    else:
        testuser = ""

    if(request.method == 'POST'):
        form = UploadImageForm(request.POST,request.FILES)
        if form.is_valid:
            imagestable = ImagesTable()
            usr = Client(username=testuser)
            imagestable.client = usr
            imagestable.title = form['title']
            imagestable.picture = form['imgfile']
            imagestable.save()
            saved = True
            return HttpResponseRedirect(reverse('myapp:upload'), {'form': form, 'saved': saved})
    else:
        form = UploadImageForm()
        return render(request, 'myapp/upload.html', {'form': form, 'saved':saved})

templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h2>This is an Online Store App</h2>
    <h4>Paged visited: {{ about_visits }} times</h4>
{% endblock %}

templates/myapp/base.html
<!DOCTYPE html>


<html>
    <head>
    {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <link rel ="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
          <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>

    <style type="text/css">


        html, body {
            height: 110%;
        }
        ul.footerbar{
            display: block;

            list-style-type: none;
        }
        li.footerli{
            padding-left: 5%;
            display: inline-flex;
        }

        footer {
            position: fixed;
            width: 100%;
            color: #666;
            background: #222;
            padding: 2px 0 2px 0;
            border-top: 1px solid #000;
            bottom: 0;
            overflow: hidden;
            margin-top: 10%;
        }
        footer a {
            color: #999;
        }
        footer a:hover {
            color: #efefef;
        }

        .container {
            max-width: 940px;
        }
        /* end responsive footer fix */


    </style>
    </head>

    <body>


    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'myapp:index' %}">MyApp</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'myapp:about' %}">Find out about this site</a></li>
        <li><a href = "{% url 'myapp:index' %}">Home </a></li>
        <li><a href = "{% url 'myapp:products' %}">Products </a></li>
          <li><a href = "{% url 'myapp:place order' %}">Place Orders </a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>

            {% if testuser %}

                <a href="#"> Hello {{testuser.username }}</a>
                <li><img src="{{ testuser.client.picture }}" height="50" width="50" /></li>
                <li> <a href="{% url 'myapp:myorders' %}">MyOrders</a> </li>
                <li> <a href="{% url 'myapp:logout' %}">Logout</a> </li>
            {% else %}
               <li> <a href="{% url 'myapp:login' %}" >Login</a></li>
        {% endif %}

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


        <div>
            <h1 style="margin-left: 40%;">Welcome To MYAPP</h1>
            <h1><!--{% block myhdg %}{% endblock %} --></h1>


            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
        <div>

        </div>
    <footer style="z-index: 2">
  <div class="container">
    <p>

        <ul class="footerbar">
                <li class="footerli"></li>
                <li class="footerli"><a href = "{% url 'myapp:index' %}">Home</a></li>
                <li class="footerli"><a href = "{% url 'myapp:about' %}">About</a></li>
                 <li class="footerli"><a href = "{% url 'myapp:products' %}">Products</a><br/></li>
                <li class="footerli"><label class="label label-success" style="float: right;"> About Page visited {{ request.COOKIES.about_visits}} times</label></li>
                <li class="footerli"><label class="label label-success" style="float: right;"> Last Login: {{ request.session.last_login}} </label></li>
        </ul>

    </p>
  </div>
</footer>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" type="text/javascript" ></script>

    </body>
</html>

templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if cat_name %}
        <h2>List of Categories</h2>
        <ol>
            <li> {{cat_name}} </li>
        </ol>

    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}

    {% if product %}
        <h2>List of Product </h2>
        <ol>
            {% for prod in product %}
                <li> {{ prod.name}} </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available Products!</strong>
    {% endif %}

{% endblock %}

templates/myapp/forgotpass.html
{% extends 'myapp/base.html' %}

{% block body_block %}

    <div class="container">
    <div class="row">
        <div class="col-md-offset-5 col-md-3">
            <form class="form-login" method="post" action="/forgotpass"> {% csrf_token %}
            <h4>Welcome back.</h4>
            <input type="text" id="email" name="email" class="form-control input-sm chat-input" placeholder="Email" />

            <div class="form-group">
            <span class="group-btn">
                <input type="submit" class="btn btn-primary btn-md" value="Login">

            </span>
            </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if cat_list %}
        <h2>List of Categories</h2>
        <ol>
            {% for cat  in cat_list %}

                <li> <a href="cat_no/{{ cat.pk }}">{{ cat.name}} </a></li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}

    {% if prod_list %}
        <h2>List of Product</h2>
        <ol>
            {% for prod  in prod_list %}
                <li> {{ prod.name}} </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available Products!</strong>
    {% endif %}

    {% ifnotequal request.session.last_login None %}
        <h4><b>Last Login: </b>{{ request.session.last_login }}</h4>
    {% else %}
        <h4><b>Last Login: </b>'Your last login was more than one hour ago'</h4>
    {% endifnotequal %}

{% endblock %}

templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <div style="padding-top: 3%" align="center">
    <div style="width: 25%;border-radius: 5px" align="center">
     <div class="col s12 z-depth-5 card-panel">
        <h4>Please Login!</h4><br/>
         {% if notlogin %}
        <div id="alert1" class="card-panel white lighten-2 red-text" style="line-height: 0; width: 65%;">
        <a href="myapp/login.html" id="close1" class="close red-text" style="vertical-align: inherit; padding-bottom: 120px" data-dismiss="alert" aria-label="close">&times;</a>
        Username or Password Wrong
        </div> <br/>
        {% endif %}
    {% if inactive %}
        <div id="alert1" class="card-panel white lighten-2 red-text" style="line-height: 0; width: 65%;">
   <a href="myapp/login.html" id="close1" class="close red-text" style="vertical-align: inherit; padding-bottom: 120px" data-dismiss="alert" aria-label="close">&times;</a>
        User is inactive.
    </div><br/>
        {% endif %}
    <form action="." method="post">{% csrf_token %}
    <div style="width: 80%">
        {{ form.as_p }}<br/>
        <button type="submit" class="btn btn-primary btn-block" value="LogIn">Login</button><br/>
    </div>
    </form>
     </div>
    </div>
    </div>
{% endblock %}

templates/myapp/myorders.html
{% extends 'myapp/base.html' %}

{% block body_block %}

{% if testuser.client %}

{% if myorder %}
    <h2>My Orders</h2>
        <table class="table">
            {% for order in myorder %}
                <tr>
                    <td>
                        {{order.product}}
                    </td>

                </tr>

            {% endfor %}
        </table>
{% else %}
        <strong>You have not placed any order!</strong>
{% endif %}

     {% else %}
        <h1>You are not a registered client</h1>
    {% endif %}

{% endblock %}

templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block body_block %}
{% if msg %}
        <h2>Message</h2>
        <h4>{{msg}}</h4>

{% else %}
        <h2>Message</h2>
        <h4>{{ msg}}</h4>
    {% endif %}
{% endblock %}

templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}

{% block body_block %}
        <form method="post">
        {% csrf_token %}
            <table border="1">
                {{ form }}
            </table>
        <button type="submit">Submit</button>
        </form>

{% endblock %}

templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
{% if prod_list %}
        <h2>List of Product</h2>
        <ol>
            {% for prod in prod_list %}
                <li><a href="{% url 'myapp:products' %}" >{{ prod.name}} </a></li>
            {% endfor %}
        </ol>

    <h2>People interested</h2>
        <ol>
            {% for prod in prod_list %}
                <li> {{ prod.interested}} </li>
            {% endfor %}
        </ol>
    <h2>Price</h2>
        <ol>
            {% for prod in prod_list %}
                <li> {{ prod.price}} </li>
            {% endfor %}
        </ol>

     <form method="post">
        {% csrf_token %}
            <table border="1">
                {{ form }}
            </table>
         <button type="submit">  Submit </button>
        </form>

    {% else %}
        <strong>There are no available Products!</strong>
    {% endif %}
{% endblock %}

templates/myapp/products.html
{% extends 'myapp/base.html' %}

{% block body_block %}
{% if prodlist %}
        <h2>List of Product</h2>
        <ol>
            {% for prod in prodlist %}
                <li> <a href="{% url 'myapp:product details' prod.pk %}"> {{ prod.name}} </a></li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available Products!</strong>
    {% endif %}
{% endblock %}